### PR TITLE
add multiple where

### PR DESCRIPTION
**Pull request by caseycs**

### CODE REVIEW

**Comment by alessandrofrancesconi** [comment]
Any news about this functionality?

**Comment by wout** [comment]
I'm also very interested in the possibility to have multiple where's. Any chance this gets implemented any time soon?

**Comment by alessandrofrancesconi** [comment]
If you are interested, I forked this repo time ago and I included this feature: https://github.com/alessandrofrancesconi/flywheel

**Comment by wout** [comment]
@alessandrofrancesconi 
Great, thanks!
But I would prefer to keep in sync with the original repo. :)

**Comment by jacmoe** [comment]
I am interested in this as well :)

**Comment by jamespsterling** [comment]
Would really love to see this

**Comment by jamesmoss** [comment]
This is now added in the latest version: https://github.com/jamesmoss/flywheel#querying

You can also do nested where clauses!

**Comment by wout** [comment]
Brilliant, thanks!

**Pull request closed without merging**
